// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD20-iDMqLelmUvFxbQ0maqQhkLbjR-QnQ',
    appId: '1:971094507020:web:f4c3ba88003d2cfefdb829',
    messagingSenderId: '971094507020',
    projectId: 'jagawarung-f99af',
    authDomain: 'jagawarung-f99af.firebaseapp.com',
    storageBucket: 'jagawarung-f99af.firebasestorage.app',
    measurementId: 'G-K9SGW9TR1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRRAiAiFPlwh5Y_hyByO6vgTxA8BMyro',
    appId: '1:971094507020:android:38823f65cfd1fb2efdb829',
    messagingSenderId: '971094507020',
    projectId: 'jagawarung-f99af',
    storageBucket: 'jagawarung-f99af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HXECOUd93tQssxDhPXOQxvJIxTGJRfw',
    appId: '1:971094507020:ios:4f6e30ae25e914bffdb829',
    messagingSenderId: '971094507020',
    projectId: 'jagawarung-f99af',
    storageBucket: 'jagawarung-f99af.firebasestorage.app',
    iosBundleId: 'com.example.jagawarung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HXECOUd93tQssxDhPXOQxvJIxTGJRfw',
    appId: '1:971094507020:ios:4f6e30ae25e914bffdb829',
    messagingSenderId: '971094507020',
    projectId: 'jagawarung-f99af',
    storageBucket: 'jagawarung-f99af.firebasestorage.app',
    iosBundleId: 'com.example.jagawarung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD20-iDMqLelmUvFxbQ0maqQhkLbjR-QnQ',
    appId: '1:971094507020:web:3d8787dec5d446fdfdb829',
    messagingSenderId: '971094507020',
    projectId: 'jagawarung-f99af',
    authDomain: 'jagawarung-f99af.firebaseapp.com',
    storageBucket: 'jagawarung-f99af.firebasestorage.app',
    measurementId: 'G-LD657TKPDK',
  );
}
